"""
Django settings for tienda_gongora project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ukj7i47@j2vaufo#9bb&$cio5(vl07=!h3cy!cb##9alh5#zyp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] 


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
    'cart',
    'orders',
    'users',
    'payments',
    'conversion',
    'tailwind',
    'theme',
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    'productos',
    'operaciones',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    # Añadir los dominios de tus sucursales y clientes externos
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}
# Configuración para JWT
from datetime import timedelta


# Configuración del paquete Simple JWT para la autenticación basada en tokens
SIMPLE_JWT = {
    # Tiempo de vida del token de acceso (usado para autenticar al usuario)
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),  # El token de acceso dura 1 día

    # Tiempo de vida del token de refresco (usado para obtener un nuevo token de acceso)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # El token de refresco dura 7 días

    # Si se establece en True, cada vez que se use un refresh token, se generará uno nuevo
    'ROTATE_REFRESH_TOKENS': False,  # En este caso, no se rotan los tokens de refresco

    # Algoritmo de encriptación utilizado para firmar los tokens
    'ALGORITHM': 'HS256',

    # Clave secreta utilizada para firmar los tokens (debe estar definida en settings.py)
    'SIGNING_KEY': SECRET_KEY,

    # Tipo de autorización en el encabezado HTTP (Authorization: Bearer <token>)
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Indica el módulo raíz que contiene las rutas (URL) del proyecto Django
ROOT_URLCONF = 'tienda_gongora.urls'  # Aquí se define el archivo principal con las URLs de la aplicación

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'tienda_gongora.middleware.RedirectByGroupMiddleware',
]

ROOT_URLCONF = 'tienda_gongora.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.categorias_api',
            ],
        },
    },
]

WSGI_APPLICATION = 'tienda_gongora.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#       'ENGINE': 'django.db.backends.mysql',
#        'NAME': 'tiendagongora',
#        'USER': 'root',
#        'PASSWORD': 'eldiablo1',  # pon tu contraseña si es que tienes
#        'HOST': '127.0.0.1',
#       'PORT': '3306',
#   }
#}

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.mysql',
#        'NAME': 'tienda_gongora',
#        'USER': 'django_user',
#        'PASSWORD': 'clave_segura_2025',
#        'HOST': 'localhost',
#        'PORT': '3306',
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tienda_gongora',
        'USER': 'django_user',
        'PASSWORD': 'clave_segura_2025',
        'HOST': 'localhost',
        'PORT': '3306',
    }
} 


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Para almacenar sesiones en la base de datos.


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_REDIRECT_URL = 'store:product_list'  # o donde desees redirigir después del login
LOGOUT_REDIRECT_URL = 'store:product_list'

LOGIN_URL = 'users:login'

BASE_URL = "54.208.45.218"


TAILWIND_APP_NAME = 'theme'