# Generated by Django 5.2 on 2025-05-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_is_paid_order_products_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buy_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
